server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: core
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ????????? ????????? ????? hibernate ? ???????? ?????? ????? liquibase
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
env:
  auth_token: test
