server:
  port: 8000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: core
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # ????????? ????????? ????? hibernate ? ???????? ?????? ????? liquibase
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true

env:
  auth-token: 516b6972-5be0-42c9-9db1-b1f52ab570ee
  not-active-days: 30
