server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: core
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.json
#  datasource:
#    username: core
#    password: core
#    url: jdbc:postgresql://localhost:5432/core
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        ddl-auto: update
#    generate-ddl: true
